#!/usr/bin/env bash

set -u

usage() {
  cat <<EOF
Usage: $0 [playbook <playbook>|update-inventory] [ANSIBLE OPTIONS]
EOF
}

test $# -eq 0 && usage && exit

INVENTORY_FILE=".vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory"
SUB_COMMAND="$1"

# Merge vagrant-inventory
test "$SUB_COMMAND" = "update-inventory" && shift && {
  sed -i -e '/Generated by vansible/,$d' $INVENTORY_FILE
  cat vagrant-inventory >> $INVENTORY_FILE
  cat $INVENTORY_FILE
  exit $?
}

# Run playbook
test "$SUB_COMMAND" = "playbook" && shift && {
  if [ $# -eq 0 ]; then
    echo "<playbook> is not specified."
    usage && exit 1
  fi
  playbook="$1"
  shift
  ansible-${SUB_COMMAND} $playbook \
          -i $INVENTORY_FILE \
          $@
  exit $?
}

# Run ansible
ansible default -i $INVENTORY_FILE $@
